### ISSUE TITLE
Default youtube emotes super large when extension is enabled

### ISSUE THREAD

**Issue by Nexxol** [Aayzie/forsens-giftbox-lidl-extension#1]
Without it enabled
![RN3XjLvR](https://user-images.githubusercontent.com/68960034/146346070-b421c4f1-7a90-40f4-97d3-c268794bd79b.png)
---------
with it enabled
![image](https://user-images.githubusercontent.com/68960034/146346198-1f5f9d62-27f3-458e-bff3-73b22d39258a.png)

( the emojis are the youtube built ones)

**Comment by Aayzie** [comment]
Windows and Chrome, right?
I'm trying out a fix right now, I'll let you know once it's published. I can't really test it on my end since it doesn't happen to me at all :(
Edit: Pog I just encountered it on firefox. For some reason, firefox puts the emojis in a separate element with an 'emoji' class, unlike chrome (on my end, at least).

**Comment by Aayzie** [comment]
Can you try out the latest version? (0.997.2)
https://chrome.google.com/webstore/detail/forsens-giftbox-lidl-exte/oobgojiochekabnidddglbpbikhnfidb

**Comment by Nexxol** [comment]
fixed
