### ISSUE TITLE
Broken video links in comments

### ISSUE THREAD

**Issue by Wruczek** [Aayzie/forsens-giftbox-lidl-extension#3]
Good job with the extension, really nice to see the emotes in comments :)

Bug report: clicking on the video link in [this pinned comment](https://www.youtube.com/watch?v=ed3Y4XzeIys&lc=UgzWfABgf8OtZt6ijEB4AaABAg) stops the currently playing video instead of navigating to the new page.

If I can ask, why is the browser history permission required? Something to do with checking the current page address?
Seems kinda snus ![](https://cdn.frankerfacez.com/emoticon/586401/1)

**Comment by Aayzie** [comment]
Thank you! :)
I'll fix that bug in a bit. Sorry for the inconvenience :( What it's doing there is it's trying to go to the 185-second mark of the current vid you're in, instead of going to the new vid.

Regarding the browser history - if you've noticed, when you visit another video on YouTube, it doesn't actually go to a new page, but rather it just changes the url and the contents of the current page. Because of this, the extension needs to detect if the url has changed or not, so that it can detect whether the user has clicked on a different vid. This is used for updating the rich description, detecting whether it's a giftbox video or not, reinitializing the emotes on comments, etc.

The extension is completely offline and doesn't send any data anywhere, so you're completely safe :)
Remember that google and mozilla reviews each extension with these permissions for multiple days, which is why it takes a long time for you guys to get my updates lol.

Thanks again for using it! Please let me know if you encounter any more issues.

**Comment by Wruczek** [comment]
Thank you for clarifying! Might be worth to add a note about history permission in the readme, so people don't get spooked.

**Comment by Aayzie** [comment]
Ah good idea, I'll do that in a bit. Thanks!

**Comment by Aayzie** [comment]
This should be fixed now in 1.6.2. Let me know if you encounter any more issues with the extension.
Thanks for the report!
